### ISSUE TITLE
While under heavy load getting error panic

### ISSUE THREAD

**Issue by nickmy9729** [VictoriaMetrics/VictoriaMetrics#215]
**Describe the bug**
Server will not start.  Getting:
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: panic: runtime error: index out of range [32] with length 32
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: goroutine 192 [running]:
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/klauspost/compress/zstd.(*fseEncoder).writeCount(0xc00d674000, 0xc0141ae000, 0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/vendor/github.com/klauspost/compress/zstd/fse_encoder.g
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/klauspost/compress/zstd.(*blockEnc).encode(0xc0002a0ee0, 0xc0002a0ee0, 0xc0052
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/vendor/github.com/klauspost/compress/zstd/blockenc.go:6
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/klauspost/compress/zstd.(*Encoder).EncodeAll(0xc0001cad80, 0xc0052e5d6e, 0x0,
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/vendor/github.com/klauspost/compress/zstd/encoder.go:47
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding/zstd.CompressLevel(0xc00a990000,
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/encoding/zstd/zstd_pure.go:43 +0x68
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding.CompressZSTDLevel(0xc00a990000, 0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/encoding/compress.go:16 +0x98
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*inmemoryBlock).marshalData(0xc0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/encoding.go:241 +0x5ec
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*inmemoryBlock).MarshalSortedDat
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/encoding.go:166 +0x98
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamWriter).WriteBlock(0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/block_stream_writer.go:167 +0x6c
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamMerger).flushIB(0xc0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/merge.go:193 +0x488
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamMerger).Merge(0xc000
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/merge.go:134 +0xf0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mergeBlockStreams(0xc00df89cd8, 0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/merge.go:35 +0x11c
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc0001ca900,
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/table.go:774 +0x4fc
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeExistingParts(0xc00
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/table.go:653 +0x120
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).partMerger(0xc0001ca900,
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/table.go:667 +0x90
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers.func1(0
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/table.go:635 +0x30
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMerg
Oct 21 04:57:16 linux-infrastructure-chicagodbaas-influx-10.novalocal victoria-metrics-pure-1.28.0.ppc64le[54144]: /root/vendor_repo/VictoriaMetrics/lib/mergeset/table.go:634 +0x68

**To Reproduce**
Unknown how to reproduce.  Instance is under heavy load and after about 1 week of running error started to occur.

**Expected behavior**
No error to occur

**Screenshots**

**Version**
1.28.0  (ppc64le pure compiled version)

**Additional context**
![image](https://user-images.githubusercontent.com/8726570/67320313-0d062600-f4dc-11e9-80e1-8b3a50184d47.png)

![image](https://user-images.githubusercontent.com/8726570/67320370-214a2300-f4dc-11e9-86a1-66e6b2ffcbb2.png)

![image](https://user-images.githubusercontent.com/8726570/67320405-332bc600-f4dc-11e9-91b7-d9eb5d081e9e.png)

![image](https://user-images.githubusercontent.com/8726570/67320450-45a5ff80-f4dc-11e9-9aa1-71827843bd1e.png)

![image](https://user-images.githubusercontent.com/8726570/67320534-59e9fc80-f4dc-11e9-8f1f-29a2ff327c31.png)

**Comment by valyala** [comment]
This looks like a bug in [pure Go zstd implementation](https://github.com/klauspost/compress/tree/master/zstd). cc'ing @klauspost  . VictoriaMetrics call concurrently [Encoder.EncodeAll](https://godoc.org/github.com/klauspost/compress/zstd#Encoder.EncodeAll) for the same [Encoder](https://godoc.org/github.com/klauspost/compress/zstd#Encoder). I suppose there is some data race in this case.

**Comment by valyala** [comment]
In the mean time you can try building VictoriaMetrics with [gozstd](https://github.com/valyala/gozstd) - Go wrapper for upstream C implementation of zstd. Run `make clean libzstd.a` inside `gozstd` directory before building VictoriaMetrics with `make victoria-metrics` on ppc64le machine.

**Comment by klauspost** [comment]
Yes. Definitely looks like something that shouldn't happen. I will take a look.

**Comment by klauspost** [comment]
@nickmy9729 v1.9.0 released which should fix the issue.

**Comment by nickmy9729** [comment]
Still getting error after using v1.9.0 of compress.  Here is stack:
[victoria_stack_trace.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3772362/victoria_stack_trace.txt)

**Comment by tenmozes** [comment]
@nickmy9729 the fix is not merged yet. PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/217

**Comment by klauspost** [comment]
This seems to be a different crash. I'll take a look.

**Comment by klauspost** [comment]
I will take a look. This looks like a logic error. I will try to see if I can set up a fuzz test for this.

If it is at all possible to grab the input sent at `VictoriaMetrics/lib/encoding/compress.go:16` when the crash happens that would be a great help.

**Comment by nickmy9729** [comment]
I am not sure I am able to do that...  Given that VictoriaMetrics uses your
library might be a steep learning curve to get that data.

-Nick

**Comment by klauspost** [comment]
Maybe it could be something like this:
```
func CompressZSTDLevel(dst, src []byte, compressLevel int) []byte {
	var finished bool
	defer func() {
		if !finished {
			ioutil.WriteFile("/tmp/crashfile.bin", src, os.ModePerm)
		}
	}()
	compressCalls.Inc()
	originalBytes.Add(len(src))
	dstLen := len(dst)
	dst = zstd.CompressLevel(dst, src, compressLevel)
	compressedBytes.Add(len(dst) - dstLen)
	finished = true
	return dst
}
```

**Comment by klauspost** [comment]
I've been running fuzz test with a hard test for this condition for 24h and still nothing, so I would really appreciate a reproduction case.

There is a small chance this could be down to a compiler error, so I will not throw in a quick workaround since that could lead to data loss (invalid stream), if that is indeed the case.

**Comment by nickmy9729** [comment]
I will put that in later tonight recompile and get you the crashfile.bin.

**Comment by nickmy9729** [comment]
@klauspost  

Here is the crashfile.bin

I have changed the extension to .zip to allow it to be posted here.  I did not zip it, just remove the .zip extention and you will have the bin file.
[crashfile.bin.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3775273/crashfile.bin.zip)

**Comment by klauspost** [comment]
Thanks! That reproduced the issue!

**Comment by nickmy9729** [comment]
@klauspost I just recompiled VictoriaMetrics with your latest patch.  So far everything is looking good.  I assume you will create a new version of compress once you have completed all your regression tests etc.

Thanks @klauspost for all your help!  You have been very generous with your time.

**Comment by klauspost** [comment]
No problem. Thanks for reporting the issue and helping to fix it. Tagging a release tomorrow.

**Comment by valyala** [comment]
@klauspost , thanks for fixing the issue!

@nickmy9729 , the issue should be fixed in the commit 6ab48838bff62228dc660580fa01ee7ed95c434c  . The fix will be available in the next VictoriaMetrics release.

**Comment by nickmy9729** [comment]
Agreed.  Been using VM with latest patch compiled and no issues.  Thanks again!

**Comment by valyala** [comment]
FYI, the bugfix is available starting from [v1.28.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
