### ISSUE TITLE
cluster version not work when upgrade

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#2419]
**Describe the bug**

when upgrade cluster version vm from 0f9aaf9ceca4c9db1b2d75a3ada1d499270a461c to 949bf25a8783a4895b4ae41026c6c2c112a11c82

after upgrade `1 vmstorage node` and `all of the vmselect node`, the query does't work(get empty result), see logs(ignore the inconsistent log time, cause i use different tz args before/after upgrade)

**Logs**
### on vmstorage node, lots of log like:
2022-04-08T05:16:07.603Z        error   VictoriaMetrics/app/vmstorage/transport/server.go:213   cannot process vmselect conn 10.168.161.60:43950: cannot process vmselect reques
t: unexpected non-zero tail left after unmarshaling SearchQuery: (len=4) "\x00\x04\x93\xe0"
...
2022-04-08T13:03:58.537+0800    error   VictoriaMetrics/app/vmstorage/transport/server.go:213   cannot process vmselect conn 10.169.220.78:54632: cannot process vmselect request: cannot unmarshal SearchQuery: cannot unmarshal MaxMetrics: too short src len: 0; must be at least 4 bytes

### on vmselect node
2022-04-08T13:17:03.762+0800    warn    VictoriaMetrics/app/vmselect/main.go:564        error in "/select/0/prometheus/api/v1/query_range?query=*******": error occured during
 search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage vmstorage-11-sf-641df-22.docker.ys:8401: cannot execute rpcName="search_v4" on vmstorage "10.168.168.21
5:8401": cannot read error message: cannot read 8 bytes with data size: EOF; read only 0 bytes

**cmd line**
### vmstorage
-storageDataPath /xxx -retentionPeriod 13 -memory.allowedPercent 45 -search.maxUniqueTimeseries 5000000 -loggerTimezone Local

### vmselect
-dedup.minScrapeInterval=1ms
-replicationFactor=2
-storageNode=node1:8401
-storageNode=node2:8401

**Comment by hagen1778** [comment]
Hi @n4mine!
This is probably a bug when RPC API version wasn't updated properly. This should be fixed at https://github.com/VictoriaMetrics/VictoriaMetrics/commit/a4a15a462b4d5481a660702675c6feb01d38e827
The issue you're facing supposed to fade away once all components will be updated to the same version.

**Comment by sharninder** [comment]
We are also seeing this bug on upgrading to 1.76.0. We have upgraded all the components and still see it. Is the fix going to be out soon ?

**Comment by hagen1778** [comment]
Hello @sharninder @n4mine!
The EOF error could also mean that vmstorage is closing established connections due to restart, so it is expected during rolling updates. Is this issue still relevant to you?

**Comment by sharninder** [comment]
@hagen1778 No, I don't think I've seen this recently.
