### ISSUE TITLE
vmbackup fails to backup to new S3 location

### ISSUE THREAD

**Issue by kenXengineering** [VictoriaMetrics/VictoriaMetrics#284]
**Describe the bug**
When running vmbackup to backup to a new, empty, location in S3, it fails attempting to delete files that do not exist.  When it attempts to delete a non-existing file, S3 returns a 403 error.

```bash
root@ip-10-0-0-202:/mnt/prometheus# vmbackup -storageDataPath=/mnt/prometheus/victoria -snapshotName=20200109180834-15E0080B73A0A7B7 -dst=s3://navistone-ken/vmbackup
2020-01-09T18:51:40.723Z        info    VictoriaMetrics@/lib/backup/s3remote/s3.go:87   bucket "navistone-ken" is stored at region "us-east-1"; switching to this region
2020-01-09T18:51:40.777Z        fatal   VictoriaMetrics@/app/vmbackup/main.go:50        cannot create backup: cannot delete `backup complete` file at S3{bucket: "navistone-ken", dir: "vmbackup/"}: cannot delete "backup_complete.ignore" at S3{bucket: "navistone-ken", dir: "vmbackup/"} (remote path "vmbackup/backup_complete.ignore"): AccessDenied: Access Denied
status code: 403, request id: 5DF9011577A28BAF, host id: zAai7PLDWxsgLzUZfW1B5FrJaK4eAhyZXoM/5K9+Eu/SmewuuBCqBx1COIGQN7OnvCXAEPGwqmg=
```

**To Reproduce**
Run vmbackup targeting an empty S3 directory.

**Expected behavior**
vmbackup should check if files exist in S3 before attempting to delete them.  

**Version**
```
vmbackup-20200109-143153-tags-v1.32.1-0-gf358fb72
```

**Comment by valyala** [comment]
Thanks for reporting the issue, @kenXengineering . It is confirmed and it will be fixed in the next release. A workaround is to use `vmbackup` and `vmrestore` from the previous release - [v1.32.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.32.0). It is safe to use `vmbackup` and `vmrestore` tools for `v1.32.1` backups.

**Comment by valyala** [comment]
The issue should be fixed in the commit b8038a14e7adc86b9bdb9d3277819eef6ed29f68 , which will be included in the next VictoriaMetrics release. @kenXengineering , could you build `vmbackup` from this commit and verify whether the issue is fixed? Steps to build `vmbackup`:
```
git clone https://github.com/VictoriaMetrics/VictoriaMetrics
cd VictoriaMetrics
git checkout b8038a14e7adc86b9bdb9d3277819eef6ed29f68
make vmbackup
```
The resulting `vmbackup` binary will be put in `bin` directory.

**Comment by valyala** [comment]
The issue should be fixed in [v1.32.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it.

**Comment by terrytaochen** [comment]
Still have this issue. I set up the VM cluster in K8S by the official helm chart.

helm chart cluster version: 0.9.45
VM image: v1.84.0
vmbackup version: v1.85.1

I can confirm S3 Key, Secret, and bucket name are correct.

![image](https://user-images.githubusercontent.com/22058876/208369826-1843a4b0-4df6-42a8-a5e0-823b7a64a007.png)
Still getting AccessDenied: Access Denied error
