### ISSUE TITLE
Nil pointer dereference in vmstorage

### ISSUE THREAD

**Issue by akamensky** [VictoriaMetrics/VictoriaMetrics#3897]
### Describe the bug

The vmstorage was (supposedly) performing final merge:

![image](https://user-images.githubusercontent.com/985805/222578733-d1cbcb30-53c2-401c-a17c-406f97e38742.png)

When it crashed with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76ad1e]

goroutine 391055 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc001b03c80, {0xc0001fe000, 0xe, 0xe}, 0xc02133ef00?, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1370 +0xafe
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeExistingParts(0xc001b03c80, 0x48?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1192 +0x388
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc001b03c80)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1064 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1051 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1050 +0x37
```

### To Reproduce

N/A

### Version

```
vmstorage-20230201-225517-tags-v1.87.0-cluster-0-g00a6ec85c
```

### Logs

```
2023-03-02T17:17:42.565Z	info	VictoriaMetrics/lib/storage/partition.go:1377	merged (11 parts, 7991405 rows, 1764755 blocks, 117031760 bytes) into (1 part, 7991403 rows, 684437 blocks, 17087424 bytes) in 564.488 seconds at 14156 rows/sec to "/storage/data/small/2023_03/7991403_684437_20230302163518.879_20230302170817.359_174822B8466465AF"
2023-03-02T17:20:13.907Z	info	VictoriaMetrics/lib/storage/partition.go:1377	merged (10 parts, 11810024 rows, 2013193 blocks, 120606280 bytes) into (1 part, 11810021 rows, 691457 blocks, 20855754 bytes) in 1523.829 seconds at 7750 rows/sec to "/storage/data/small/2023_03/11810021_691457_20230302161910.937_20230302165449.462_174822B84664655F"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76ad1e]

goroutine 391055 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc001b03c80, {0xc0001fe000, 0xe, 0xe}, 0xc02133ef00?, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1370 +0xafe
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeExistingParts(0xc001b03c80, 0x48?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1192 +0x388
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc001b03c80)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1064 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1051 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1050 +0x37
2023-03-02T17:50:26.340Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmstorage-20230201-225517-tags-v1.87.0-cluster-0-g00a6ec85c
2023-03-02T17:50:26.341Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2023-03-02T17:50:26.341Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="10s"
2023-03-02T17:50:26.341Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -memory.allowedPercent="10"
2023-03-02T17:50:26.341Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="90d"
2023-03-02T17:50:26.341Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/storage"
```

### Used command-line flags

See the log above for CLI arguments.

### Additional information

The time difference between log and graph is due to vmstorage running in container as UTC, the crash is shortly before the drop in disk space usage.

**Comment by hagen1778** [comment]
Hello @akamensky! Thanks for report!
Did it happen to all storage nodes? Did you call force-merge? Does it happen consistently?

**Comment by f41gh7** [comment]
Related commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/8189770c50165b62867327ad388f2c2ef237ab6f

 Issue could happen, when merging only in-memory parts.

**Comment by akamensky** [comment]
@hagen1778 Happened only on 1 node that I presume was doing final merge for last month data. See the screenshot - yellow graph node is the one that crashed _before_ the drop in size. The assumption that it was doing final merge based on the disk space usage build up since there were no log entries mentioning final merge.

We didn't do any force merge attempts on that or other nodes.

**Comment by hagen1778** [comment]
Hi @akamensky! Thanks for report!
The issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3900 and will be available in the next release.

**Comment by akamensky** [comment]
@hagen1778 When possibly a patch release would happen with this fix? 

* I updated vmstorage to 1.81.1, that did not fix it
* It now consistently happening on the same node now with the same symptoms:
  * the storage size grows (no log entries for final merge)
  * at some point it crashes with null pointer dereference
  * After start it seems to cleanup storage and immediately start doing same thing

The relevant log and screenshot:

```
2023-03-04T17:18:08.495Z	info	VictoriaMetrics/lib/storage/partition.go:1400	merged (12 parts, 45338435 rows, 3128110 blocks, 149010500 bytes) into (1 part, 45275091 rows, 691792 blocks, 35486200 bytes) in 351.740 seconds at 128897 rows/sec to "/storage/data/small/2023_03/45275091_691792_20230304163755.000_20230304171216.017_1748C1C2211E1CDD"
2023-03-04T17:19:33.600Z	info	VictoriaMetrics/lib/storage/partition.go:1400	merged (1 parts, 3726580 rows, 684598 blocks, 13336576 bytes) into (1 part, 3726580 rows, 684598 blocks, 9720201 bytes) in 348.989 seconds at 10678 rows/sec to "/storage/data/small/2023_03/3726580_684598_20230304171156.561_20230304171339.823_1748C1C2211E1CE7"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x741ede]

goroutine 282 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc0001fe480, {0xc0029bc000, 0xb, 0xc}, 0x0?, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1393 +0xafe
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeExistingParts(0xc0001fe480, 0x48?)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1215 +0x33c
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc0001fe480)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1087 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1074 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
	github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1073 +0x37
2023-03-04T18:05:43.774Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmstorage-20230228-021935-tags-v1.88.1-cluster-0-g223bb6f36
2023-03-04T18:05:43.774Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2023-03-04T18:05:43.774Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="15s"
2023-03-04T18:05:43.774Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -memory.allowedPercent="10"
2023-03-04T18:05:43.774Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="90d"
2023-03-04T18:05:43.774Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/storage"
```

![image](https://user-images.githubusercontent.com/985805/222988286-7ca30225-80b1-493a-80d3-0577d3b4eca4.png)

**Comment by f41gh7** [comment]
Can you try following docker image for vmstorage `victoriametrics/vmstorage:v1.88.3-rc1-cluster`?

 Or you can build it from sources from [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/361e1b1165cb68ac5f7fb279f208c704618093dc)

 [doc how to build](https://docs.victoriametrics.com/#how-to-build-from-sources)

**Comment by akamensky** [comment]
The issue seems to be happening even not with final dedups (happened again yesterday).

Thanks @f41gh7 I've updated to the 1.88.3-rc1 image and running it now, will update if still see this issue.

**Comment by akamensky** [comment]
@f41gh7 been running 1.88.3-rc1 for a 2 days, didn't have any panics with that so far.

**Comment by valyala** [comment]
@akamensky , thanks for the confirmation that the panic has been fixed! The bugfix has been included in [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.

**Comment by valyala** [comment]
FYI, the bugfix has been also included in [v1.87.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.3).
