### ISSUE TITLE
victoriametrics metrics missing

### ISSUE THREAD

**Issue by system51** [VictoriaMetrics/VictoriaMetrics#5948]
### Describe the bug

Using victoriametrics v1.99.0, I found that some host indicators could not be collected.  Other versions had no problems and no error messages were reported in the logs.Collection is normal through prometheus, but victoriametrics is not collected. (Same node_exporter)

### To Reproduce

use  `victoria-metrics-20240301-013527-tags-v1.99.0-0-g9cd4b0537` 

### Version

[root@geepaas-yunpingtai-infraprometheus ~]# ./victoria-metrics-prod --version
victoria-metrics-20240301-013527-tags-v1.99.0-0-g9cd4b0537

### Logs

nothing

### Screenshots

![a3a86178f0c6c4ef75dee191008197de](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26198108/f90b38e1-ce3e-4d12-9a64-968ddc140bb6)

![13ba21e5ba980a2a2b3203978a85cdc3](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26198108/a8cfdb4a-43bd-4b18-bea4-70142d6ac52c)

![c093fb9791d0ff37a24d803abbdd2c86](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26198108/9032e365-76c9-46ce-973e-94cf323487f2)

### Used command-line flags

VICTORIAMETRICS_OPT=-http.connTimeout=5m \
-maxConcurrentInserts=20000 \
-maxInsertRequestSize=100MB \
-maxLabelsPerTimeseries=20000 \
-insert.maxQueueDuration=5m \
-dedup.minScrapeInterval=60s \
-retentionPeriod=180d \
-search.maxQueryDuration=10m \
-search.maxQueryLen=30MB \
-search.maxQueueDuration=60s \
-search.maxConcurrentRequests=32 \
-storageDataPath=/usr/local/victoriametrics/data \
-promscrape.config=/usr/local/victoriametrics/conf/prometheus.yml \
-vmui.defaultTimezone="Asia/Shanghai" \

**Comment by liyu36** [comment]
I encountered the same problem. When using Helm deployment, data written through vmagent or Prometheu will be lost. The problem only occurs in version 1.99.0

<img width="1895" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/81213315/033e1b6e-9e26-4dbd-b4c3-bae7db31af26">

**Comment by zekker6** [comment]
@system51 Could you check `http://<victoriametrics>:8428/targets` page and see if node_exporter is listed there and shows no errors?

@ilyatrefilov Could you elaborate on what do this graphs represent? Also, it would be great if you could also check if the targets are visible on `/targets` page in vmagent after the upgrade.

**Comment by liyu36** [comment]
> @ilyatrefilov Could you elaborate on what do this graphs represent? Also, it would be great if you could also check if the targets are visible on `/targets` page in vmagent after the upgrade.

I started three clusters using k3s and respectively started Prometheus agents in cluster 1 and cluster 2, both configured with remote write to send data to Prometheus, VM (version 1.97.1), and VM (version 1.99.0) in the third cluster. Data can be queried normally in Prometheus and VM (version 1.97.1), but some metrics are missing in VM (version 1.99.0). The PromQL used in the Grafana dashboard above is the PromQL in the panel title.

When using PrometheusAgent or vmagent for indicator collection, the target is visible on the collection end.

**Comment by hagen1778** [comment]
@zekker6 @system51 it is likely related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5959

**Comment by system51** [comment]
@liyu36  I think we both have the same problem

**Comment by system51** [comment]
@zekker6    
![c051bf1ec0167ddfff27bba5e9d54012](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26198108/9f8513ad-c873-4689-9dd4-b688fabc36c5)



```
[root@geepaas-yunpingtai-infraprometheus conf]# curl -s http://10.168.141.194:9100/metrics | grep 'mode="idle"'
node_cpu_seconds_total{cpu="0",mode="idle"} 1.386557309e+07
node_cpu_seconds_total{cpu="1",mode="idle"} 1.36568373e+07
node_cpu_seconds_total{cpu="10",mode="idle"} 1.382141433e+07
node_cpu_seconds_total{cpu="11",mode="idle"} 1.381492997e+07
node_cpu_seconds_total{cpu="12",mode="idle"} 1.383049954e+07
node_cpu_seconds_total{cpu="13",mode="idle"} 1.382304469e+07
node_cpu_seconds_total{cpu="14",mode="idle"} 1.383795742e+07
node_cpu_seconds_total{cpu="15",mode="idle"} 1.383173461e+07
node_cpu_seconds_total{cpu="16",mode="idle"} 1.383554286e+07
node_cpu_seconds_total{cpu="17",mode="idle"} 1.383765774e+07
node_cpu_seconds_total{cpu="18",mode="idle"} 1.383782668e+07
node_cpu_seconds_total{cpu="19",mode="idle"} 1.384312045e+07
node_cpu_seconds_total{cpu="2",mode="idle"} 1.369365772e+07
node_cpu_seconds_total{cpu="20",mode="idle"} 1.384849986e+07
```

**Comment by system51** [comment]
@hagen1778 i'will continue to monitor the progress of this issue

**Comment by ulope** [comment]
I also seem to have run into this issue.

I've just deployed a new monitoring setup with relatively high cardinality (~57k) and by accident discovered that an unknown number of series were missing for the first ~2 hours of the run.

A VM restart seems to have "fixed" whatever was broken. 
Logs of the source prove that the issue is within VM.

Needless to say that this is highly disturbing. A monitoring system that returns wrong data is worse than no monitoring (IMO).

I've now redeployed with 1.93.13 and all series seem to be available instantly.

![Screenshot 2024-03-14 at 22 32 29](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55078/083492df-2665-4784-98bf-b1e2aa721dd6)

The step shown in the attached screenshot is what I'm talking about and is not present in the source data.

**Comment by valyala** [comment]
@system51 , @liyu36 , could you build VictoriaMetrics from the commit 76f00cea6b9bf02a262275a112040c2680ed472c according to [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether this helps resolving the issue with missing metrics?

**Comment by liyu36** [comment]
> [76f00ce](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/76f00cea6b9bf02a262275a112040c2680ed472c)

The issue of missing metrics was not resolved after using 76f00ce to build, and the value of the `vm_missing_metric_mames_for_metric_id_total` metric remained at 0.

**Comment by ulope** [comment]
Would this fix still work when the metric in question has a scrape interval >60s?

**Comment by system51** [comment]
@liyu36  i'm version 1.98.0 

```
victoria-metrics-20240214-141141-tags-v1.98.0-0-gbaaa88001
```


![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26198108/82854ca5-3494-45ef-b838-521bc68d5b9c)

**Comment by mustdiechik** [comment]
the same issue. rollback to vm/victoria-metrics-single chart 0.9.15  with image  v1.97.1 work`s fine.

**Comment by valyala** [comment]
@system51 , side notes regarding the command-line flags for VictoriaMetrics listed at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5948#issue-2178023600 :

> -maxConcurrentInserts=20000

The `-maxConcurrentInserts` command-line flag limits the number of concurrently processed inserts by VictoriaMetrics. There is no sense in setting it higher than the number of available CPU cores multiplied by some small constant (such as 2), since every CPU core can process only a single concurrent insert at the given time. The small multiplier may be needed for processing concurrent inserts over slow network connections when the bottleneck is in network transfer speed instead of CPU.

Too big values for `-maxConcurrentInserts` may result in the increased RAM usage for VictoriaMetrics without any benefit on the overall data ingestion speed.

There were issue in the previous versions of VictoriaMetrics, which could require setting high values for `-maxConcurrentInserts`:

- The `-maxConcurrentInserts` was incorrectly applied when scraping targets defined at [`-promscrape.config`](https://docs.victoriametrics.com/sd_configs/). This has been fixed in [v1.94.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.94.0) - see [the corresponding pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5073).
- The `-maxConcurrentInserts` was incorrectly applied for idle client connection. This has been fixed in [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.86.0) in [this commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c63755c316b71630d2f090e3ff7f2fbd36f9cccc).


> -maxInsertRequestSize=100MB

The `-maxInsertRequestSize` limits the maximum size of a single request for [data ingestion](https://docs.victoriametrics.com/#how-to-import-time-series-data). Too big value for this command-line flag may result in high RAM usage when processing big data ingestion requests.

> -maxLabelsPerTimeseries=20000

The `-maxLabelsPerTimeseries` limits the number of labels a single [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) can have during data ingestion. Too big number of labels per every time series may result in high RAM usage, slow data ingestion, high disk space usage and slow query performance. Too high number of labels per time series usually points to some configuration issues either at scrape target side or at [scrape config](https://docs.victoriametrics.com/sd_configs/) side, which must be fixed.

In general, it is recommended minimizing the number of command-line flags passed to VictoriaMetrics components, since most of these flags have sane default values, which work for most cases. If you think that some flags have not so optimal default values, then please file [an issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/), so we could fix this in upcoming releases.

**Comment by valyala** [comment]
> Would this fix still work when the metric in question has a scrape interval >60s?

The root cause of the issue is that VictoriaMetrics could delete newly registered [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) in a few seconds after it has been registered. The time series is deleted because VictoriaMetrics couldn't find its' name plus all its labels in the inverted index (aka `metricID->metricName` entry in the `indexdb`) when the time series is found in some search query results. VictoriaMetrics assumes that the inverted index is incomplete for the given time series, so it drops the time series, so it could be registered again. The inverted index may miss recently added entries after unclean shutdown (such as out of memory (OOM) crash, `kill -9` or hardware power off) or after restoring from [snapshot](https://docs.victoriametrics.com/#how-to-work-with-snapshots), if the recently added entries aren't flushed from in-memory storage to persistent storage yet.

The code responsible for deleting the time series if the `metricID->metricName` isn't found in `indexdb` exists in VictoriaMetrics since 2019. Why it triggers with much higher probability starting from [v1.99.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.99.0)? Because of optimizations added in `v1.99.0`, which improve the registration speed for new time series - 73f0a805e2d8ee55ea4e94b8cb19e3d43c3ac31d and bace9a25011d9175f9fa6861e129f8ed8f9e0521 . As a side effect, these optimizations increase the delay between registering new entries in the `indexdb` and appearance of these entries in search results. This increased chances that the `metricID->metricName` entries for newly registered time series aren't visible for search for a few seconds after their registration.

[The bugfix](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/76f00cea6b9bf02a262275a112040c2680ed472c) postpones deletion of time series data for up to 60 seconds when it cannot find the corresponding `metricID->metricName` entry in `indexdb`. The newly registered `metricID->metricName` entries become visible for search after a few seconds, so 60 seconds delay should be enough in most cases. **This logic doesn't depend on the scrape interval, so it works with arbitrary scrape intervals.**

## How to detect whether you are affected by the issue?

Look at the `vm_missing_metric_names_for_metric_id_total` [metric](https://docs.victoriametrics.com/#monitoring). If you are affected by the issue, then this metric should increase over time with some constant speed. E.g. `increase(vm_missing_metric_names_for_metric_id_total[5m])` [query](https://docs.victoriametrics.com/metricsql/) should return some non-zero value over long time ranges.

## How to detect whether the issue is fixed?

The `vm_missing_metric_names_for_metric_id_total` metric should stop growing after the upgrade to 76f00cea6b9bf02a262275a112040c2680ed472c or newer commit.

**Comment by valyala** [comment]
> The issue of missing metrics was not resolved after using https://github.com/VictoriaMetrics/VictoriaMetrics/commit/76f00cea6b9bf02a262275a112040c2680ed472c to build, and the value of the vm_missing_metric_mames_for_metric_id_total metric remained at 0.

@liyu36 , does the `vm_missing_metric_names_for_metric_id_total` metric grow over time at a constant speed at `v1.99.0` on your workload?

**Comment by system51** [comment]
@valyala Thanks, I will optimize my parameters.

**Comment by system51** [comment]
> > The issue of missing metrics was not resolved after using [76f00ce](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/76f00cea6b9bf02a262275a112040c2680ed472c) to build, and the value of the vm_missing_metric_mames_for_metric_id_total metric remained at 0.
> 
> @liyu36 , does the `vm_missing_metric_names_for_metric_id_total` metric grow over time at a constant speed at `v1.99.0` on your workload?

`vm_missing_metric_names_for_metric_id_total`     What is the role of indicators

**Comment by dctrwatson** [comment]
Just noticed this happening. However, `vm_missing_metric_names_for_metric_id_total` is `0` 
Even after downgrading to v1.97.1 the metrics still were not available via query. Nor were they available via `/api/v1/export`.

To restore metrics, also had to restart the known affected services which changes their labelset.

**Comment by valyala** [comment]
@system51 , @dctrwatson , could you upgrade to [v1.100.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.100.0) and verify whether this prevents from dropping newly registered time series?

Note that the upgrade doesn't restore data for old time series, which could be dropped while `v1.99.0` was running - it should prevent from dropping **newly ingested samples** for all the time series - already registered and new ones.

**Comment by valyala** [comment]
> `vm_missing_metric_names_for_metric_id_total` What is the role of metrics

This metric is increased every time VictoriaMetrics cannot find the `metricID->metricName` entry in the inverted index (aka `indexdb`). This may happen more frequently at `v1.99.0` because it may delay the visibility of added inverted index entries in search results as described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5948#issuecomment-2022565212).

**Comment by dctrwatson** [comment]
> @system51 , @dctrwatson , could you upgrade to [v1.100.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.100.0) and verify whether this prevents from dropping newly registered time series?

The metrics that saw immediate disappearance after v1.99.0 upgrade, did not disappear with v1.100.0 upgrade
It's now been a few days and after spot checking, doesn't look like we've lost any metrics since then.
So it seems like this issue is solved for us. Thank you!

Another nice improvement, is we used to see periodic persistent queueing in vmagent, that has also stopped.

**Comment by system51** [comment]
@dctrwatson @valyala    I haven't started testing yet.

**Comment by system51** [comment]
@parkjeongryul   OK, thank you. I think this bug has been fixed.

**Comment by hagen1778** [comment]
The fix for properly registering new entries in IndexDB when many new time series are ingested into VictoriaMetrics in a short period of time was released in [v1.100.1](https://docs.victoriametrics.com/changelog/#v11001)

**Comment by system51** [comment]
@hagen1778 @valyala   I want to know about VictoriaMetrics storage principle。

**Comment by valyala** [comment]
> I want to understand the VictoriaMetrics storage principle, such as prometheus tsdb. Is there any relevant literature?

There are the following docs, which can help understanding how VictoriaMetrics stores data:
* [high-level overview on how storage layer works in VictoriaMetrics](https://docs.victoriametrics.com/#storage)
* [various technical articles on VictoriaMetrics architecture](https://docs.victoriametrics.com/articles/#technical-articles)
* [source code of the `lib/storage` package](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/lib/storage) - it is used for storing `(timestamp, value)` pairs for the ingested [time series](https://docs.victoriametrics.com/keyconcepts/#time-series)
* [source code of the `lib/mergeset` package](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/lib/mergeset) - it is used for storing inverted index aka `indexdb`.

Closing the issue as fixed in [v1.100.1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.100.1).

**Comment by Haleygo** [comment]
JFYI, the fix was also included in LTS [v1.97.4+](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.4).
