### ISSUE TITLE
Empty metric name in the Grafana dropdowns

### ISSUE THREAD

**Issue by Allineer** [VictoriaMetrics/VictoriaMetrics#600]
**Describe the bug**

Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/599

<img width="743" alt="Снимок экрана 2020-07-02 в 15 38 02" src="https://user-images.githubusercontent.com/1168049/86359712-08545d00-bc7a-11ea-80b5-b0fe17d3fd34.png">

Did you see an empty dropdown item before the "alertmanager"?

**Comment by valyala** [comment]
The issue should be fixed in the commit 0b2086b7a57175211841d913b6034db61ab0407b . This commit will be included in the next release. In the mean time the bugfix may be tested by building VictoriaMetrics from the commit according [to these docs](https://victoriametrics.github.io/#how-to-build-from-sources).

**Comment by Allineer** [comment]
@valyala seems, it's working for me. Thanks.

But I still can’t understand where they come from. I do not have rules that delete all labels and the name of the metric itself.

Exporters used are almost from the list https://github.com/prometheus/prometheus/wiki/Default-port-allocations and, I hope, do not allow yourself to export an empty metric with only a value.

There are two custom exporters, but all the metrics that they exports are all written to the database, all are available.

**Comment by Allineer** [comment]
Maybe it makes sense to add to vmagent the logging of metrics that he is trying to write to the database without a name AND labels? Perhaps it will turn out to get at least some additional information and the answer to the question "Who is to blame?" - vmagent, vm-node or exporters?

**Comment by valyala** [comment]
FYI, the commit that prevents from adding and/or selecting metrics with empty label values has been included in [v1.38.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by Allineer** [comment]
Thanks!
