### ISSUE TITLE
vmagent is not recovering after network storm/instability

### ISSUE THREAD

**Issue by ofen** [VictoriaMetrics/VictoriaMetrics#628]
**Describe the bug**
vmagent is not recovering after network storm/instability. http://vmagent-host:8429/targets says that everything is ok and scrapping in progress but according to Grafana there are no metrics after network issue. Also there was no any logs during the issue (no error/warn/panic/info records).

**To Reproduce**
Network issue required

**Expected behavior**
vmagent continues to send metrics after the remote host becomes available

**Screenshots**
[![grafana.jpg](https://i.postimg.cc/MKQSchM0/grafana.jpg)](https://postimg.cc/zV8M62k3)

**Version**
v1.37.4

**Used command-line flags**
* -promscrape.config=/config/scrape.yaml
* -remoteWrite.url=https://<remote_victoriametrics_database>/api/v1/write
* -promscrape.configCheckInterval=30s

**Workaround**
Restart vmagent pod

**Comment by valyala** [comment]
@ofen , could you look into `vmagent` logs during time range when it stopped sending data to the configured `-remoteWrite.url`?

**Comment by ofen** [comment]
[logs 14.07](https://pastebin.com/embed/eU4Y0p3W)

**Comment by valyala** [comment]
Unfortunately these logs don't contain any information which could point to the issue with the stopped data push to `-remoteWrite.url`. Could you upgrade to the latest `vmagent` version and check whether the issue is still reproduced there? See https://github.com/VictoriaMetrics/VictoriaMetrics/releases

**Comment by KrepakVitaly** [comment]
@ofen Is the situation was repaired?

I have the similiar situation -- after lost connection and re-establish it I lost metrics on grafana.
I used the last ver of `vmagent` for ARM (Raspberry Pi) and `victoriametrics` for remote server (Ubuntu 18) 

I've run this cmd in conslole:

`./vmagent-arm -promscrape.disableKeepAlive -enableTCP6 -promscrape.config=./prometheus.yml remoteWrite.url=http://<ip>:8428/api/v1/write &>log_vmagent &`

Logs of `vmagent`:
```
2020-07-26T09:17:53.983Z        info    app/vmagent/remotewrite/client.go:123   initialized client for -remoteWrite.url="http://remote-ip:8428/api/v1/write"
2020-07-26T09:17:53.984Z        info    lib/promscrape/scraper.go:78    reading Prometheus configs from "./prometheus.yml"
2020-07-26T09:17:53.984Z        info    lib/httpserver/httpserver.go:77 starting http server at http://:8429/
2020-07-26T09:17:53.984Z        info    app/vmagent/main.go:99  started vmagent in 0.022 seconds
2020-07-26T09:17:53.984Z        info    lib/httpserver/httpserver.go:78 pprof handlers are exposed at http://:8429/debug/pprof/
2020-07-26T09:17:53.991Z        info    lib/promscrape/scraper.go:303   static_configs: added targets: 1, removed targets: 0; total targets: 1
2020-07-26T09:20:02.993Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": EOF; re-sending the block in 2.000 seconds
2020-07-26T09:20:07.994Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": dialing to the given TCP address timed out; re-sending the block in 4.000 seconds
2020-07-26T09:20:14.996Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": dialing to the given TCP address timed out; re-sending the block in 8.000 seconds
2020-07-26T09:20:25.997Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip.103:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": dialing to the given TCP address timed out; re-sending the block in 16.000 seconds
2020-07-26T09:20:42.004Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip.103:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": http: ContentLength=2170 with Body length 0; re-sending the block in 32.000 seconds
2020-07-26T09:21:14.012Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip.103:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": http: ContentLength=2170 with Body length 0; re-sending the block in 60.000 seconds
2020-07-26T09:22:14.020Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip.103:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": http: ContentLength=2170 with Body length 0; re-sending the block in 60.000 seconds
2020-07-26T09:23:14.027Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": http: ContentLength=2170 with Body length 0; re-sending the block in 60.000 seconds
2020-07-26T09:24:14.034Z        error   app/vmagent/remotewrite/client.go:210   couldn't send a block with size 2170 bytes to "http://remote-ip:8428/api/v1/write": Post "http://<remote-ip>:8428/api/v1/write": http: ContentLength=2170 with Body length 0; re-sending the block in 60.000 seconds
```

After killing and restart the vmagent the metrics restores, but no historical data
![image](https://user-images.githubusercontent.com/6016636/88475858-75d37080-cf3c-11ea-8628-8ba9fdf9cc72.png)


`prometheus.yml` :

```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8000']
```

**Comment by valyala** [comment]
@KrepakVitaly , the `http: ContentLength=... with Body length 0` error has been fixed in `v1.39.1` - see [release notes](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) for details.

**Comment by valyala** [comment]
Try updating to vmagent [v1.39.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and verify whether the issue still exists.

**Comment by KrepakVitaly** [comment]
> Try updating to vmagent [v1.39.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and verify whether the issue still exists.

Hello, thanks

After update vmagent to v1.39.2 it starts sendning data after restored connection and the situation is really much more better.
And the small issue is still there -- the data in random time period between 30s to 10 min after connection instability is lost

But at the same time the promethteus server also scrapes data from the same client that vmagent scrapes, could it lead to the such data lost? 

I've not experimented yet, after experiment I will update this comment

`prometheus.yml` :

```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8000']
```

**Comment by valyala** [comment]
> But at the same time the promethteus server also scrapes data from the same client that vmagent scrapes, could it lead to the such data lost?

This may be the case only if the scrape target is very slow, so multiple concurrent scrapes could drop it. BTW, try upgrading to [v1.39.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - it contains additional bugfixes for `vmagent`, which could lead to frequent reconnects. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/663

**Comment by valyala** [comment]
@ofen , @KrepakVitaly , is the issue still reproducible in the latest available version of vmagent ([v1.59.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) now)?

**Comment by ofen** [comment]
@valyala hi, so far so good. Except that we use 1.53.1 due to memory footprint issue.

**Comment by valyala** [comment]
Do you mean the issue described at  https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1235 ?

**Comment by ofen** [comment]
> Do you mean the issue described at #1235 ?

Yeah, and #1167

**Comment by valyala** [comment]
Thanks! Then closing this issue as outdated.
