### ISSUE TITLE
Migration from Prometheus-agent to vmagent

### ISSUE THREAD

**Issue by juliocleal14** [VictoriaMetrics/VictoriaMetrics#7144]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hello everyone, I hope you’re doing well.

I would greatly appreciate any guidance on migrating from Prometheus-Agent to VMAgent.

We started the conversation [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6424), and it is better to create a new one to bring more visibility.

cc: @hagen1778, @AndrewChubatiu

We’ve been using Prometheus-Agent since migrating from Thanos to VictoriaMetrics two years ago. 

We initially chose this approach because we have a large Prometheus configuration file and wanted to avoid spending time revising it.

Recently, we reached out for assistance here regarding some unusual spikes in our histogram metrics. This issue was raised, and @hagen1778  recommended migrating to VMAgent as a solution.

We are currently working on it and encountering several challenges during the migration process.

Our scenario is:

* We are running VictoriaMetrics in cluster mode, deployed on Kubernetes.

* We’re implementing the [high availability approach](https://docs.victoriametrics.com/vmagent/#high-availability) for VMAgent by deploying 2 pods to scrape all targets. Deduplication is applied before forwarding the time series data to VMInsert/VMStorage.

* We are running the VMAgent on version `v1.103.0`, while the others VictoriaMetrics components are on version `v1.95.1`.

Below how we are running each component:

### VMAgent

```
/vmagent-prod \
        --promscrape.suppressScrapeErrors=true \
        --promscrape.suppressDuplicateScrapeTargetErrors=true \
        --promscrape.maxScrapeSize=400MB \
        --promscrape.streamParse=true \
        --promscrape.config=/vmagent.yml \
        --remoteWrite.maxDiskUsagePerURL=95GiB \
        --remoteWrite.queues=32 \
        --remoteWrite.maxBlockSize=50MiB \
        --remoteWrite.maxRowsPerBlock=10000 \
        --loggerFormat=json \
        --remoteWrite.showURL=true \
        --remoteWrite.url=http://vminsert_address:8480/insert/0/prometheus/api/v1/write \
        --remoteWrite.tmpDataPath=/vmagent/data \
        --promscrape.cluster.name=$(POD_NAME) \
        --remoteWrite.streamAggr.dedupInterval=30s \
        --streamAggr.dropInputLabels=replica \
        --http.maxGracefulShutdownDuration=60s 
```

### VMStorage

```
/vmstorage-prod \
        --storageDataPath=/storage \
        --retentionPeriod=4d \
        --search.maxUniqueTimeseries=300000 \
        --dedup.minScrapeInterval=30s \
        --loggerFormat=json \
        --storage.vminsertConnsShutdownDuration=210s \
        --cacheExpireDuration=30m0s \
        --internStringCacheExpireDuration=6m0s \
        --memory.allowedPercent=60 \
        --prevCacheRemovalPercent=0.1 \
        --storage.minFreeDiskSpaceBytes=20GB \
        --precisionBits=64
```

### VMInsert

```
/vminsert-prod \
        --disableRerouting=false \
        --dropSamplesOnOverload=false \
        --maxLabelsPerTimeseries=60 \
        --replicationFactor=2 \
        --loggerFormat=json \
        --loggerFormat=json \
        --disableRerouting=false \
        --dropSamplesOnOverload=false \
        --maxLabelsPerTimeseries=60 \
        --replicationFactor=2 \
        --vmstorageDialTimeout=2s \
        --vmstorageUserTimeout=2s \
        --maxConcurrentInserts=15 \
        --storageNode=vmstorage-0:8400 \
        --storageNode=vmstorage-1:8400 \
        --storageNode=vmstorage-2:8400 \
        --storageNode=vmstorage-3:8400 \
        --storageNode=vmstorage-4:8400 \
        --storageNode=vmstorage-5:8400
```

So, we are trying understand some things:

1. I understand that a direct comparison may not be possible, but with Prometheus-Agent, we were using 13 vCPUs, whereas with VMAgent, we’ve configured 35 vCPUs, and it still hasn’t been sufficient.

## VMAGent vCPU

![image](https://github.com/user-attachments/assets/05463fbe-4e1b-42bf-9196-abf97ba69574)

## Prometheus agent vCPU

![image](https://github.com/user-attachments/assets/ecdb986a-3c9c-4060-8f6e-f38d266e24a3)

I came across a related [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5898) concerning a similar problem with aggregation enabled, although the user had a different configuration. I only require aggregation for deduplication purposes, nothing else.

I’ve adjusted the values for `remoteWrite.queues`, `remoteWrite.maxBlockSize`, and `remoteWrite.maxRowsPerBlock` in an attempt to decrease resource usage, but haven’t achieved the desired results. 

After several attempts, I believe I’ve identified a relationship between the configuration parameters and the scraped data points.

As shown in the Scrape Datapoints graph, we have around 500k datapoints scraped per second. If I configure `remoteWrite.maxRowsPerBlock` to 500k and set `remoteWrite.queue` to 60, I would expect the queues to fill in 60 seconds, correct? With this setup, I would just need to ensure that the datapoints are sent within that 60-second window to avoid storing them in the persistent queue, right?

![image](https://github.com/user-attachments/assets/473c3a63-ea7e-4282-b337-e7bdf8515c49)

So, I configured the VMAgent with the following values:

```
--remoteWrite.queues=64 \
--remoteWrite.maxBlockSize=400MiB \
--remoteWrite.maxRowsPerBlock=500000 \
```

With this configuration, I was able to get VMAgent working—at least it started sending metrics to the remote storage.

However, we began to notice some unusual values in various graphs. Take a look at these examples:

![image](https://github.com/user-attachments/assets/ddca7df5-d68c-4b92-b69b-d312cb752b29)

Explaing better the graphs: The graphs come from our ‘Monitoring of Monitoring’ setup, which is a Prometheus instance running with a few days’ retention, specifically scraping metrics from our monitoring tools.

The first two graphs show CPU and memory usage of VMAgent, using Prometheus as the data source. The last two graphs display the same CPU and memory usage, but with VictoriaMetrics as the data source, using metrics sent by VMAgent

As you can see, the graphs are significantly different. The graphs using metrics sent by VMAgent have fewer datapoints, and the values seem slightly off compared to those collected by Prometheus.

*My question is: Could this behavior be caused by a configuration issue on my end? I’m unsure why this is happening.*

Another observation is that with this configuration, we see a substantial increase in VMInsert and VMStorage resource usage, and, the resource usage of the VMAgent continue high. Take a look at the following data:

## VMInsert

![image](https://github.com/user-attachments/assets/48979879-2e6d-4049-8389-516b2bfd573f)

## VMStorage

![image](https://github.com/user-attachments/assets/e49cbb22-102c-4bd3-bb84-9cfde6b6dcc3)

![image](https://github.com/user-attachments/assets/b3b88d85-fc97-4af3-af43-40eea4dad5e1)

![image](https://github.com/user-attachments/assets/a1fd3e6a-bb0a-47ad-89e3-bbe6a8d3ecb0)

## VMAgent

![image](https://github.com/user-attachments/assets/305a8a04-8d25-4347-999f-815017fd1da3)

I understand that we need to make some adjustments to resource usage, but it seems to me that everything is worse when using VMAgent.

2. During the restart of VMAgent, we observe spikes in the Grafana graphs. It appears that this may be due to buffered time series being added out of order, with all of them being stored with the same timestamp?

This first image shows when I restarted the VMAGent

![image](https://github.com/user-attachments/assets/350ebb74-dcd7-4bf6-aea4-153fe43265c1)

The second metric represents HTTP request latency, which shows significant behavior changes during the VMAgent restart. This could be problematic, as it may lead to false alerts or misleading information in the graphs.

![image](https://github.com/user-attachments/assets/2c2217ae-d891-4746-b7ba-32ba185187cd)

I saw this flag: 

`streamAggr.ignoreFirstIntervals`: 

> Number of aggregation intervals to skip after the start for aggregator. Increase this value if you observe incorrect aggregation results after vmagent restarts. It could be caused by receiving unordered delayed data from clients pushing data into the vmagent. See https://docs.victoriametrics.com/stream-aggregation/#ignore-aggregation-intervals-on-start

Could this flag resolve the issue? If so, what is the rationale for selecting the optimal value?

3. I’ve noticed an unusual relationship between the rows inserted by VMInsert and disk utilization in VMStorage. My understanding is that fewer rows being inserted would require less disk space in VMStorage to store the metrics, however, it seems that this is not the case, look the graphs:

Please split the graphs into three sections:

a. Before 9/24, noting a brief gap around 18:00 separating.

b. The time between letter A and 9/25 around 18:00 (noting an another bried gap to separate)

c. After 9/25 at 18:00, highlighting the subsequent changes.

The letters A and C we were using Prometheus-agent and the letter b we were using VMAgent

We can observe a growth in the disk space utilization while we were using VMAgent.

![image](https://github.com/user-attachments/assets/486cba73-6434-432e-ba3a-740f0fe5def0)

But the stranger thing is: When we observe the rows inserted in the same interval we can see a significant difference between usage.

![image](https://github.com/user-attachments/assets/23b48387-1048-4f7c-8bef-1967aad47227)

Is this correct? 

4. The streamParse could cause a delay in the metrics send to remote storage? (I ask this because the VMAgent will process the responses in chunks async, right?)

To summarize, I understand that migrating to VMAgent could help reduce the spikes in the histogram graphs. However, I believe VMAgent may not be well-suited for our scenario. I’m currently testing it in a small staging environment, while our main production environment is at least five times larger.

Do you have any advice for us to make VMAgent functional? We need to consider the financial implications of this decision. Preliminary calculations suggest that we would need to triple our current monitoring costs to support the migration, and ultimately, this may not be the best choice for us.

If we decide not to use VMAgent, do you have any suggestions for addressing these spikes? I noticed that [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442), which aimed to ensure that timeseries from the same histogram metrics are routed to the same VMStorage by VMInsert, has been closed. Could this have been a viable solution? Alternatively, is there a newer version of VictoriaMetrics that resolves this issue in another way?

Thank you very much in advance. I realize I’ve provided a lot of information, so please feel free to ask for any additional details or to separate the problems into different parts.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by juliocleal14** [comment]
@hagen1778, the part of the doc that I understood that, to run in HA I need has deduplication enabled is [here](https://docs.victoriametrics.com/vmagent/#high-availability), particularly in this sentense 

> When running HA pairs, [deduplication](https://docs.victoriametrics.com/#deduplication) must be configured at VictoriaMetrics side in order to de-duplicate received samples. See [these docs](https://docs.victoriametrics.com/#deduplication) for details.

**Comment by juliocleal14** [comment]
I had understood that VMAgent performs deduplication through stream aggregation. However, as seen in Pic2, VMAgent has the `-dedup.minScrapeInterval` flag, correct? To enable this, it seems I would need one VMAgent to scrape data and another in between to deduplicate before sending to remote write. This means I would need two VMAgent components: one for scraping (handling retries, etc.) and a second dedicated to deduplication and forwarding data to VMInsert. Did I understand this correctly?

Currently, it’s not possible to use the same VMAgent in a HA pair for deduplication, meaning deduplication only occurs at the VMStorage/VMSelect level, and the data is stored in duplicate, right?

**Comment by hagen1778** [comment]
> This means I would need two VMAgent components: one for scraping (handling retries, etc.) and a second dedicated to deduplication and forwarding data to VMInsert. Did I understand this correctly?
I want to avoid store duplicated data and use vmstorage/vmselect to deduplicate (they already have tasks a lot to worry about deduplication)

You can have vmagent in the middle with dedup enabled. But honestly, I don't see how double writes into storage would affect it to much. VM is pretty efficient at this, and most of the users set deduplication on storage and read level. And since you have RF > 1 you already need to dedup on read path. So not the big change compared to adding an extra component to the chain.

> And in this vmagent-in-the-middle I would set it as a deployment with a hpa, for example ?

With HPA you'd have to configure scraping vmagents to shard data by chosen labels across replicas of deduplicators.  Which sounds non-trivial. Do you have HPA for scrapers as well?

**Comment by juliocleal14** [comment]
> With HPA you'd have to configure scraping vmagents to shard data by chosen labels across replicas of deduplicators. Which sounds non-trivial. Do you have HPA for scrapers as well?

No, I use statefulset currently. I was asking about hpa in the vmagent in the middle, but, anyway, in my opinion, if I add a vmgent in the middle I will add a more one single point of failure in my metrics path, what I think is not a good idea

I disabled the stream aggregatiom on vmagent in the environment I am testing and, in fact, the cpu usage decrease, like we can see in the graphs

## Without stream aggregation
![image](https://github.com/user-attachments/assets/f1ab2926-cad4-449f-be14-e454a71f6783)

## Without stream aggregation
![image](https://github.com/user-attachments/assets/8cb63716-0ce0-4024-84f4-61de2607c3e6)

**Comment by hagen1778** [comment]
> But, I think the cpu usage is still so much, is there any initiative looking for this?

Sure! Could you please post the following items:
1. The current list of cmd-line flags configured on vmagent.
2. vmagent version
3. vmagent [cpu and mem profiles](https://docs.victoriametrics.com/vmagent/#profiling)
4. Screenshot of grafana dashboard for vmagent: stats, overview section, resource usage and scraping sections.

**Comment by valyala** [comment]
It would be great also to see the initial configuration for the scheme with Prometheus agents, in order to make sure the scheme with vmagent instances works in the same way.

1. Do you use identical scrape configs for Prometheus agent and vmagent?
2. How do you configure HA with Prometheus agents?
3. Do Prometheus agent and vmagent discover the same set of targets? Do they scrape the same set of targets? Do they scrape the same set of metrics from these targets? See [these docs](https://docs.victoriametrics.com/vmagent/#debugging-scrape-targets) for answering these questions.

Also you suppress errors during target discovery and target scraping at vmagents according to the following command-line flags:

```
-promscrape.suppressScrapeErrors
-promscrape.suppressDuplicateScrapeTargetErrors
```

Probably there are some errors at vmagent, which result in increased resource usage? It is better fixing these errors instead of suppressing them.

**Comment by juliocleal14** [comment]
Hi @hagen1778 , sorry for delay in answer you. I was traveling last week.

1. The current list of cmd-line flags configured on vmagent.
```
        - --promscrape.suppressScrapeErrors=true
        - --promscrape.suppressDuplicateScrapeTargetErrors=true
        - --promscrape.maxScrapeSize=400MB
        - --promscrape.config=/etc/vicmetrics-agent/vicmetrics-agent.yml
        - --remoteWrite.maxDiskUsagePerURL=95GiB
        - --remoteWrite.queues=64
        - --remoteWrite.maxBlockSize=400MiB
        - --remoteWrite.maxRowsPerBlock=500000
        - --loggerFormat=json
        - --remoteWrite.showURL=true
        - --remoteWrite.url=http://VMINSERT_ADDRESS:8480/insert/0/prometheus/api/v1/write
        - --remoteWrite.tmpDataPath=/tmp/vicmetrics-agent/data
        - --promscrape.cluster.name=$(POD_NAME)
        - --http.maxGracefulShutdownDuration=60s
```

2. vmagent version

`v1.103.0`

3. vmagent [cpu and mem profiles](https://docs.victoriametrics.com/vmagent/#profiling)

[profile.zip](https://github.com/user-attachments/files/17280212/profile.zip)

4. Screenshot of grafana dashboard for vmagent: stats, overview section, resource usage and scraping sections.

## Stats

![stats](https://github.com/user-attachments/assets/fa244fdb-cb38-4235-b7f7-bebd32ffda5b)

## Overview

![overview](https://github.com/user-attachments/assets/5f7accc8-7be5-4d2d-aa19-2d7bf157c4b0)

## Resource usage

![resource_usage_01](https://github.com/user-attachments/assets/90f8d12b-f023-4b9d-8279-ad4d4ee3bc87)
![resource_usage_02](https://github.com/user-attachments/assets/8b63c202-fdea-4e85-a339-41738e3ab282)

## Scrape
![scrape_01](https://github.com/user-attachments/assets/342bcc9a-b020-4053-b419-033419df4ce1)
![scrape_02](https://github.com/user-attachments/assets/af9ea3e0-e88c-48f5-a5c2-56bb74ac9f88)
![scrape_03](https://github.com/user-attachments/assets/9b1dada6-ab2c-463c-a271-1cc915a43cc0)

**Comment by juliocleal14** [comment]
Hi @valyala , thank you so much for your answer.

Yes, the prometheus and vmagent uses the same config file (I use a jinja template and only use if and env var to remove the unsupported configs in the vmagent (like remote_write section in the prometheus-agent) but, this jinja file is the same used in both.

So, they scrape the same list of targets, they have the same relabel config (because they use the same config file). 

So, I could show the errors removing the flags that are suppresing the errors, but, I think the Prometheus-agent get the same errors because they scrape the same targets, this only would be different if vmagent handle with errors different than Prometheus, but I think it is not true because the vmagent has Prometheus compatibility, right?

**Comment by hagen1778** [comment]
Hi @juliocleal14 !
Thanks for detailed response.
According to attached profiles, the most of the CPU time is spent on Garbage Collecting caused by applying extra labels to all generated series. While this is usually a typical load, in this case it generates extra allocations because of conflicts between existing label and extra label. This process accounts for 54% of all allocations that happen during processing: 
<img width="552" alt="image" src="https://github.com/user-attachments/assets/ac666a50-367a-4594-b5c6-189bdfec58fa">

So my question is what is that external label you apply, that are likely to **exist in most of the scraped series** and are likely **conflicting** with the external label setting. The reason why I ask is that it is the first time I see such behavior.

-------------

As for vmagent accumulating the queue - can I ask to attach the following screenshots of Grafana dashboard:
1. vmagent. Remote write section. 
2. VM cluster. vminsert and vmstorage sections.

vmagent could be facing [issues on sending data](https://docs.victoriametrics.com/vmagent/#troubleshooting) in 3 cases:
1. Lack of resources. vmagent looks pretty overloaded, but according to screenshots it still has some spare CPU
2. Network bandwidth limit. This happens rarely.
3. Receiving side being slow. This is likely what is happening, so I want to check if vminserts and vmstorages are fine.

-------------

Side note.        
 - --remoteWrite.maxBlockSize=400MiB and  - --remoteWrite.maxRowsPerBlock=500000 aren't something that usually needs to be touched. If receiving side is in stable state and has resources, then defaults should do just fine. Returning these params back should also decrease the memory usage of vmagent.

**Comment by juliocleal14** [comment]
Hi @hagen1778 ,

About the queue getting accumulated, I'm not actually sending the collected metrics to a vminsert. Since I'm still solving these issues in the vmagent, I'm leaving the Prometheus-agent running and, to upload and test things, I'm sending it to a dummy vminsert, so that's the only reason why the queues are accumulating. I'll worry about that after I solve the cpu usage.

About the external labels, what you're saying is that my "original" timeseries already have the labels that I'm adding later as external labels? And since this causes conflict, the vmagent is using a lot of cpu trying to adjust this via relabel, right?

As I said above to @valyala , I use the same configuration file in prometheus, and I know that, obviously, the way Prometheus handles these conflicts is different from the way the vmagent handles these conflicts. The problem is that I have several jobs, so I believe that in some target, in some job, these external labels are actually added and cause conflict, but this certainly does not happen with all targets of all jobs, and for this reason I cannot remove it.

One question.

If I configure my vmagent to do sharding, according to this [documentation](https://docs.victoriametrics.com/vmagent/#scraping-big-number-of-targets), mixing the ha configuration with the sharding configuration, as follows:

memNumbers=6, replicationFactor=2, will I still have ha because of the replicationFactor?

**Comment by hagen1778** [comment]
> About the queue getting accumulated, I'm not actually sending the collected metrics to a vminsert. Since I'm still solving these issues in the vmagent, I'm leaving the Prometheus-agent running and, to upload and test things, I'm sending it to a dummy vminsert, so that's the only reason why the queues are accumulating. I'll worry about that after I solve the cpu usage.

I'd suggest then to set the following cmd-line flags:
```
  -remoteWrite.disableOnDiskQueue array
     Whether to disable storing pending data to -remoteWrite.tmpDataPath when the remote storage system at the corresponding -remoteWrite.url cannot keep up with the data ingestion rate. See https://docs.victoriametrics.com/vmagent#disabling-on-disk-persistence . See also -remoteWrite.dropSamplesOnOverload
     Supports array of values separated by comma or specified via multiple flags.
     Empty values are set to false.
  -remoteWrite.dropSamplesOnOverload
     Whether to drop samples when -remoteWrite.disableOnDiskQueue is set and if the samples cannot be pushed into the configured -remoteWrite.url systems in a timely manner. See https://docs.victoriametrics.com/vmagent#disabling-on-disk-persistence
```
And reset all other --remoteWrite.* flags to default values. Otherwise, vmagent does a lot of extra work that is not needed.

> As I said above to @valyala , I use the same configuration file in prometheus, and I know that, obviously, the way Prometheus handles these conflicts is different from the way the vmagent handles these conflicts. The problem is that I have several jobs, so I believe that in some target, in some job, these external labels are actually added and cause conflict, but this certainly does not happen with all targets of all jobs, and for this reason I cannot remove it.

Is it possible to temporary remove the extra labels setting and observe if it is indeed a root cause of elevated CPU usage? If it is, we can think of optimizing this. But first I want to be sure.

> memNumbers=6, replicationFactor=2, will I still have ha because of the replicationFactor?

With these settings you can lose up to 1 vmagent without losing any scraped data.

**Comment by hagen1778** [comment]
> Is that way we ask me to test?

Yes. Can I have cpu and mem profile for vmagent running like this?

**Comment by juliocleal14** [comment]
> Yes. Can I have cpu and mem profile for vmagent running like this?
Of course, I missed, sorry.

[Archive.zip](https://github.com/user-attachments/files/17299372/Archive.zip)

**Comment by hagen1778** [comment]
Thank you! According to profiles, the allocations for external labels disappeared. But on the screenshots it didn't give much results, maybe about 5% CPU decrease. Hence, there is not much sense in optimizing this path.
So I guess it is what it takes to handle this load. I'll try to investigate profiles in more details later. But so far I don't see any outstanding code parts, so this is expected resource usage behavior according to profiles.

I'm a bit concerned about spiky resource usage: memory and CPUs jump all the time. I don't know if this is an artifact of the monitoring itself or caused by the volatility of discovered targets.

**Comment by juliocleal14** [comment]
> I'm a bit concerned about spiky resource usage: memory and CPUs jump all the time. I don't know if this is an artifact of the monitoring itself or caused by the volatility of discovered targets.

I observed this too.  I am testing in a staging environment that thas a lot of spot nodes in the kubernetes cluster, this make the pods being recreated every time, maybe this behavior is about this, but I don't know 

To advance in my initial problem (Spikes in histogram metrics) I am trying applying [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442) sending the histogram timeseries for the same vmstorage.
In the `v1.95.1` version didn't work, I am trying in the `v1.103.0` I holpe that work.

After this test using Prometheus-agent I will trying replace the Prometheus-agent by vmagent in this environment applying the sharding configuration to try solve the other problems I sent in the initial message, and I hope that work


Thank you so much for now and congratulations for your hard work in help the users!

**Comment by juliocleal14** [comment]
hi @hagen1778 , how are you?

> To advance in my initial problem (Spikes in histogram metrics) I am trying applying https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442 sending the histogram timeseries for the same vmstorage.

I implemented this and tested in my staging environment, but this solution does not work to solve the spikes in histogram queries, so, I came back for the 0 stage

So, I go ahead and I am trying again running the vmagent on this environment with a different configuration.


```
- --promscrape.suppressScrapeErrors=true
        - --promscrape.suppressDuplicateScrapeTargetErrors=true
        - --promscrape.maxScrapeSize=400MB
        - --promscrape.config=/etc/vicmetrics-agent/vicmetrics-agent.yml
        - --promscrape.cluster.membersCount=12
        - --promscrape.cluster.memberNum=$(POD_NAME)
        - --promscrape.cluster.replicationFactor=2
        - --loggerFormat=json
        - --remoteWrite.maxDiskUsagePerURL=95GiB
        - --remoteWrite.queues=64
        - --remoteWrite.maxBlockSize=9MiB (I a declarating this here, but I am using the default value)
        - --remoteWrite.maxRowsPerBlock=10000 (I a declarating this here, but I am using the default value)
        - --remoteWrite.showURL=true
        - --remoteWrite.tmpDataPath=/tmp/vicmetrics-agent/data
        - --remoteWrite.url=http://$(NU_ENV)-$(NU_PROTOTYPE)-$(NU_STACK_ID)-vicmetrics-insert.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
        - --promscrape.cluster.name=$(POD_NAME)
        - --http.maxGracefulShutdownDuration=60s
```

Look that, I broke my instalation in 12 pods with replicationFactor 2 to simulate the same HA I need. 

In both configuration (this one and in the configuration using only 2 pods in HA) I experimented some in cascade problems. 

The vminsert became reaching the concurrent inserts, look in the graphs

![Screenshot 2024-10-10 at 4 42 55 PM](https://github.com/user-attachments/assets/5eb70682-3bb3-422a-98cc-247c12716902)


The vmstorage started to meet the resource limit

![Screenshot 2024-10-10 at 4 40 19 PM](https://github.com/user-attachments/assets/104b3515-1647-45d0-b9fe-d24a39c73dd0)

The vmstorage disk space increased too

![Screenshot 2024-10-10 at 4 44 51 PM](https://github.com/user-attachments/assets/f0f79ee7-ae52-4265-b977-bab942e8c9ec)

The vmstorage disk read became with a strange behavior too

![Screenshot 2024-10-10 at 4 45 37 PM](https://github.com/user-attachments/assets/447e1172-7bc2-49cf-8631-bccab31016b2)



So, to summarize

I tried solve the spikes with a suggestion change in the vminsert, that not work, and when I try to deploy the vmagent again, I have other problems.

I think I am doing something a really so much wrong in the configuration, but I don't know where.

Could you help understand the better way to deploy the vmagent ?

**Comment by juliocleal14** [comment]
Hi @hagen1778 , 
I would like to understand better how the vmagent sharding works.

In the example above, in a cluster with 6 vmagent intances with replicationFactor 2.

This means that, my number of targets will be divide by 3, right?

My questions are:

1. How the vmagent cluster knows one each other?
2. What happens with the targets scraped for if a vmstorage instance become unavailable (restarting the pod, for example) ? How the vmagent rebalance the targets in the others instances?

**Comment by hagen1778** [comment]
Sorry for the late reply.

> I implemented this and tested in my staging environment, but this solution does not work to solve the spikes in histogram queries, so, I came back for the 0 stage

As I understand, the problem with spikes in histograms was solved [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6424#issuecomment-2281942244):
>We tested the VMAgent for the couple weeks and using the VMAgent in fact the problem does not occour.
However, I am trying understand the difference between the vmagent and the Prometheus in this specific situation.
Why with the VMAgent this did not occour?

Did it start to happen again?


> I only obseved that the disk utilization has a growth rate bigger than Prometheus, look the graph

Is the ingestion speed the same as it was with Prometheus? By saying "Prometheus", do you mean Prometheus-agent?

> In the example above, in a cluster with 6 vmagent intances with replicationFactor 2.
This means that, my number of targets will be divide by 3, right?

This means that each target in your list is scraped by at least 2 agents (replicationFactor 2). And each agent scrapes `(num_of_targets * 2) / 6` targets.

 > How the vmagent cluster knows one each other?

They don't know about each other. Each vmagent gets the full list of targets to scrape. It then uses `--promscrape.cluster.membersCount` and `--promscrape.cluster.memberNum` to calculate the hash function over the list of targets. For example, if you have 100 targets to scrape and vmagent with `--promscrape.cluster.membersCount=4` `--promscrape.cluster.memberNum=1` settings, then it will scrape first 25 targets. Another vmagent with `--promscrape.cluster.memberNum=2` will scrape 25-50 targets, and so on.

> What happens with the targets scraped for if a vmstorage instance become unavailable (restarting the pod, for example) ? How the vmagent rebalance the targets in the others instances?

vmstorage availability has no effect on sharding or routing strategy of vmagent. 
vmagent is configured to send data to vminserts. If vminsert is unavailable, vmagent just starts to queue unsent data on the disk (local filesystem) and continues to scrape or receive writes. If queue exceeds disk capacity, vmagents starts to drop the oldest entries in the queue. If remote url (vminsert) becomes available again - vmagent drains its queue by sending data ASAP.

**Comment by juliocleal14** [comment]
> As I understand, the problem with spikes in histograms was solved https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6424#issuecomment-2281942244:

Not really. We tested change the prometheus-agent to vmagent, but only this change did not solve the problem.
In my uncontable tests, the only solution that worked is using vmagent + [this implementation](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442) (I created a local version with this implementation to test)

Only change to vmagent did not solve. 
I understand the @valyala comment [here](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442#issuecomment-2395334618) but, for now it is the only solution we have to the spikes. 

The solution consists in migrate to vmagent AND implement the if, and, I understand it is not a good solution, but for now it is the only I have. 

About the problems in the migration, the only problem remainder is about high cpu utilization, all others I solved adjusting the vmagent parameters.


> vmstorage availability has no effect on sharding or routing strategy of vmagent.
vmagent is configured to send data to vminserts. If vminsert is unavailable, vmagent just starts to queue unsent data on the disk (local filesystem) and continues to scrape or receive writes. If queue exceeds disk capacity, vmagents starts to drop the oldest entries in the queue. If remote url (vminsert) becomes available again - vmagent drains its queue by sending data ASAP.

I wrote wrong here. My question is about vmagent. If 1 or more vmagent pod become unavailable in the same time, how the vmagent rearrange the targets to each vmagent?

**Comment by hagen1778** [comment]
> Not really. We tested change the prometheus-agent to vmagent, but only this change did not solve the problem.

This is weird. Spikes shouldn't happen if the following conditions are met:
1. The scraped target doesn't expose its own timestamps, so vmagent can assign the same timestamp to samples scraped in the same time
2. Deduplication happens correctly, without conflicts described in the previous ticket.
3. All vmstorage nodes in VM cluster are returning their results during read query execution.

Despite the fact that vmagent shards series belonging to the same histogram across many vmstorage nodes, the series should be consistent on every given timestamp eventually. There might be inconsistency for last 30s or so, while data is still delivering or sits in the buffers. But after that - everything should be correct.

Can I have raw data for a histogram which still produces spikes? Please, try to find as small dataset as possible for this.
Could you also confirm that VM cluster is stable during calculations or if spikes are jumping (changing their place) on every query?

>I wrote wrong here. My question is about vmagent. If 1 or more vmagent pod become unavailable in the same time, how the vmagent rearrange the targets to each vmagent?

They don't re-balance, because they're not aware of each other. But vmagents shouldn't rebalance themselves, their restart time shouldn't take more than 10s.

**Comment by juliocleal14** [comment]
> This is weird. Spikes shouldn't happen if the following conditions are met:

The scraped target doesn't expose its own timestamps, so vmagent can assign the same timestamp to samples scraped in the same time
Deduplication happens correctly, without conflicts described in the previous ticket.
All vmstorage nodes in VM cluster are returning their results during read query execution.

The timeseries does not have any timestamps, and, we have spikes about metrics produced for our kubernetes pods and for metrics produced for third party services, I think this is not a problem.

> There might be inconsistency for last 30s or so, while data is still delivering or sits in the buffers. But after that - everything should be correct.

In the past we already tried configured the `latencyOffset` and other similar flags, to try look for a bit more past, but it did not have effect in the spikes.


> Could you also confirm that VM cluster is stable during calculations or if spikes are jumping (changing their place) on every query?

I thought the problem could be related to vmstorage resources, and I increased a lot the cpu and memory to test, I checked every dashboard and I cannot see any strange behavior.

> Can I have raw data for a histogram which still produces spikes? Please, try to find as small dataset as possible for this.

of course yes. Do you have a suggestion of how I can extract this data?

**Comment by hagen1778** [comment]
> of course yes. Do you have a suggestion of how I can extract this data?

Yes, please follow p2 from https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results

**Comment by hagen1778** [comment]
> The spikes happen using query in the current timestamp (like the vmalert do to evaluate a alert), when I do the same query using a query_range the spikes do not happen.

This is weird. I do see spikes on query_range requests:
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/74b6b0cc-5f6e-46d7-a066-176b7321704b">

Am I right to assume, that these metrics arent' pre-aggregated or pre-calculated in any way? That they're going directly from vmagents scraping them from their targets?

The spikes, after closer looks, appear because of some of the buckets updated before other buckets:
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/c7844020-5991-4d4e-b2f0-99c66476dd15">


On the screenshot, you see that bucket 15 was updated before bucket 90, which can't be if data was scraped at the same moment of time.
Further investigation shows some uneven distribution of samples within these series:
* Series with le=0.2 got its first update of the value to "110" at 2024-10-23 19:07:01 +0200 CEST
* Series with le=90  got its first update of the value to "110" at 2024-10-23 19:07:16 +0200 CEST, 15s later.

The step between datapoints within a series is also weird: most of the samples are distanced by 30s, but some of them - by 15s:
```
2024/10/25 11:55:02 step diff is 30s at 1729706416611 (2024-10-23 20:00:16 +0200 CEST): 191
2024/10/25 11:55:02 step diff is 0s at 1729706416611 (2024-10-23 20:00:16 +0200 CEST): 191
2024/10/25 11:55:02 step diff is 14s at 1729706431040 (2024-10-23 20:00:31 +0200 CEST): 192
2024/10/25 11:55:02 step diff is 16s at 1729706446611 (2024-10-23 20:00:46 +0200 CEST): 192
2024/10/25 11:55:02 step diff is 0s at 1729706446611 (2024-10-23 20:00:46 +0200 CEST): 192
```

This makes me think that something of the following could happen:
1. vmagents are configured to scrape the same job with different scrape_interval
2. vmselects aren't configured with the same --dedup.minScrapeInterval or its value is different to --dedup.minScrapeInterval on vmstorage side

Can we verify this is not the case?

**Comment by juliocleal14** [comment]
Thanks a lot for the help @hagen1778 

> Am I right to assume, that these metrics arent' pre-aggregated or pre-calculated in any way? That they're going directly from vmagents scraping them from their targets?

We do nothing. We only scrape and send the timeseries to vminsert.  On the vminsert we have some limits configured like the `maxLabelsPerTimeseries`, but I think this could not be a problem, right?
Below, the vminsert parameters we are running:

```
/vminsert-prod --disableRerouting=false --dropSamplesOnOverload=false --maxLabelsPerTimeseries=50 --replicationFactor=2 --loggerFormat=json --loggerFormat=json --disableRerouting=false --dropSamplesOnOverload=false --maxLabelsPerTimeseries=55 --replicationFa
ctor=2 --vmstorageDialTimeout=2s --vmstorageUserTimeout=2s --maxConcurrentInserts=15 --storageNode=vmstorage-0:8400 --storageNode=vmstorage-1:8400 --storageNode=vmstorage-n:8400
```

> The step between datapoints within a series is also weird: most of the samples are distanced by 30s, but some of them - by 15s

This is really very, very weird. We scrape the kubernetes pods in the same prometheus job. 

> vmagents are configured to scrape the same job with different scrape_interval

```
- job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    scheme: https
    honor_labels: true
    sample_limit: 600000
    bearer_token_file: token_path
    tls_config:
      insecure_skip_verify:  true
      cert_file: cert.pem
      key_file: cert.key
    relabel_configs:
    - relabel_configs
    metric_relabel_configs:
    - metric_relabel_configs
```


```
global:
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels:
    external_labels_here
```

This job uses a global scrape_interval configuration that is 30 seconds.

I checked in the original raw I extracted and all lines had the same job label, so, it is possible to guarantee the all timeseries sent for you came from the same job and with the same scrape_interval (30s)


> vmselects aren't configured with the same --dedup.minScrapeInterval or its value is different to --dedup.minScrapeInterval on vmstorage side

the vmselect parameters

```
/vmselect-prod --vmalert.proxyURL=http://vmalert-address:8880 --http.connTimeout=130s --http.idleConnTimeout=80s --http.maxGracefulShutdownDuration=40s --search.maxUniqueTimeseries=300000 --search.maxQueryDuration
=35s --search.minStalenessInterval=5m --search.maxQueryLen=48KB --search.latencyOffset=30s --search.maxConcurrentRequests=38 --search.maxMemoryPerQuery=500000000 --dedup.minScrapeInterval=30s --loggerFormat=json --replicationFactor=2 --search.logQueryMemoryUsage=450MB --storageN
ode=vmstorage-0:8401 --storageNode=vmstorage-1:8401 --storageNode=vmstorage-n:8401
```

the vmstorage parameters:

```/vmstorage-prod --storageDataPath=/storage --retentionPeriod=8d --search.maxUniqueTimeseries=300000 --dedup.minScrapeInterval=30s --loggerFormat=json --storage.vminsertConnsShutdownDuration=210s --cacheExpireDuration=30m0s --internStringCacheExpireDuration=6
m0s --memory.allowedPercent=60 --prevCacheRemovalPercent=0.1 --storage.minFreeDiskSpaceBytes=40GB --precisionBits=64
```

As you can see, both dedupScrapeInterval are configured with 30 seconds.


It is really, really weird, after your investigation. It seems that everything is ok but, not!

**Comment by juliocleal14** [comment]
hello everyone!
About vmagent CPU performance I think we figured out a good solution.
The VMAGent uses the GOGC in 30% as default.
When I was reading [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7832#issuecomment-2545907788) in another issue, I observed that, in our scenario, we have around 40k of targets everytime and a `scrape_size` above 200MiB.
This setup match with said in the comment: more or less like this: "If you scrape a lot of targets and if the response size is big, consider using the GOGC in 100% instead 30%"
When I tested the GOGC in 100%, I decreased the vmagent vcpu from 22 to 12 vCPU, but I needed to increase (of course) the memory from 27GiB to 35GiB.
Like our vCPU cost has a more weight instead memory cost, in our scenario was a good idea change the vCPU resource to memory resource usage. 
Of course, each environment is different and I'm not sure if this configuration could be applied for everyone.

About the spikes in histogram timeseries, the only way we found to resolve is apply the implementation of [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442). We are considering create a fork of the VM to apply this implementaion ourselves

**Comment by hagen1778** [comment]
I am closing this issue due to lack of activity. It seems like the most of the questions regarding resource usage were addressed. And https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442 is out of scope.
