### ISSUE TITLE
Query with "or on() vector(0)" return an extra data series

### ISSUE THREAD

**Issue by van0828** [VictoriaMetrics/VictoriaMetrics#7640]
### Describe the bug

When query like this `up{job="apiserver"} or on() vector(0)`, vm returns an extra data series that was not within my expect. Its has a data series which value is 0 and has no labels, but I think the `or on() vector(0)` is only used for the `up{job="apiserver"}` has no value. My vm version is v1.106.0

v1.106.0 ui screenshot:
![image](https://github.com/user-attachments/assets/e4dc601b-b30c-45ac-9063-9923ddff5366)

And I run the same query in v1.103.0, its return correct data series
v1.103.0 ui screenshot:
![image](https://github.com/user-attachments/assets/42b30d4a-8118-4a3a-8c31-e467375737ff)

### To Reproduce

None

### Version

v1.106.0

**Comment by van0828** [comment]
PS: v1.106.1 also has this problem

**Comment by jiekun** [comment]
Hi! Sorry for the late reply. I'm refactoring the `or on(condition)` logic in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7770. The pull request should fix this issue as well.

**Comment by jiekun** [comment]
This should be fixed by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8164 and will be included in next release. You can also build VictoriaMetrics/vmselect from master/cluster branch to verify. Please let me know if any help needed

**Comment by zekker6** [comment]
Fix was included in relases [v1.110.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.110.1), [v1.102.13](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.13) and [v1.111.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.111.0). Closing as completed.

**Comment by clavinjune** [comment]
this one is still happening on v1.114.0-cluster version, is this expected @zekker6? I'm using below query

```
up{job="apiserver"} or vector(0)
```

<img width="412" alt="Image" src="https://github.com/user-attachments/assets/c9acb493-084f-42a1-8abe-819379a55085" />

**Comment by clavinjune** [comment]
I'm trying this query https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.114.0-cluster/app/vmselect/promql/exec_test.go#L9445

<img width="1110" alt="Image" src="https://github.com/user-attachments/assets/9f3e4467-7cb5-4d13-82cd-7ba7262de540" />

and it's still off @jiekun

**Comment by jiekun** [comment]
@clavinjune This should be a different case (might be relevant tho), as the pull request fix case for:
```
up{job="apiserver"} or on() vector(0)
```

According to Prometheus's doc:
> `vector1 or vector2` results in a vector that contains all original elements (label sets + values) of vector1 and additionally all elements of vector2 which do not have matching label sets in vector1.

So it could be correct to include such empty series in the result. ~~But the prometheus does remove this in the result. I think we should try to align with PromQL.~~

~~So thanks for the bug report, would you mind opening a new issue to track this?  I'd like to take a look later.~~

Aha sorry I made a wrong test on Prometheus. Please see [this one](https://play.grafana.org/explore?schemaVersion=1&panes=%7B%22fsu%22:%7B%22datasource%22:%22grafanacloud-prom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7B__name__%3D%5C%22up%5C%22,%20asserts_env%3D%5C%22faro-shop%5C%22,%20cluster%3D%5C%22faro-shop%5C%22,%20container%3D%5C%22alloy%5C%22,%20instance%3D%5C%2210.244.0.13:12345%5C%22,%20job%3D%5C%22integrations%2Falloy%5C%22,%20namespace%3D%5C%22faro-shop%5C%22,%20pod%3D%5C%22grafana-k8s-monitoring-alloy-events-5cbd9f9f76-wgt8x%5C%22%7D%20or%20vector%280%29%22,%22range%22:true,%22instant%22:false,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22grafanacloud-prom%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-30d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1).

**Comment by clavinjune** [comment]
got it, hence the `on()` is needed on scalar, thanks a lot @jiekun
