### ISSUE TITLE
VictoriaLogs web UI: sort log field names in alphabetical order

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#8438]
### Is your feature request related to a problem? Please describe

[VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) doesn't sort log fields at the `Group` and `JSON` views. This complicates investigation of logs with big number of fields, since it is hard to locate the particular field across hundreds of field names. See, for example, [logs at this playground link](https://play-vmlogs.victoriametrics.com/select/vmui/?#/?query=%7Btype%3DPullRequestEvent%7D&g0.range_input=1d&g0.end_input=2025-03-02T23%3A00%3A00&g0.relative_time=none&view=json).

### Describe the solution you'd like

It would be great to sort log fields by field name at the `Group` and `JSON` views. This will significantly simplify investigating logs with big number of fields like in the example above.

**Comment by hagen1778** [comment]
The sorting behavior was fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8816. Now fields are sorted by key in the Group tab. This change will be included into the next vlogs release.

**Comment by yuriydzobak** [comment]
Hi,
Thanks for great work!
I want to mention the next information

I checked this build
```
version:
victoria-logs-20250501-081725-heads-master-0-gcafb847544-dirty-da39a3ee
```

1. This fix does not resolve the problem of incorrect sorting in the table view, as described in this issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8774
![Image](https://github.com/user-attachments/assets/b4916853-2730-4b54-96a4-897470fbfbed)

2. I don't know if it excepted, but in group view, before `_time,_msg,_stream` had harcoded position, when time is always first
How it was before
![Image](https://github.com/user-attachments/assets/cad279ad-ee21-40e8-8a13-63a9b455bbd3)
now it. What is fine
![Image](https://github.com/user-attachments/assets/50379dcd-f7ea-485f-8ea1-b5383bf7aea4)

but it can create a probelm when logs has fields that starts `_` and then it sorting as well. _Note: i understand nameing field is not good_

<img width="1418" alt="Image" src="https://github.com/user-attachments/assets/0cd9a778-dcac-42db-b7cb-e1a0c7586523" />


My proposal is that system fields such as `_time, _msg, _stream, and _stream_id` should be positioned at the top in the group view.  Something like excluding them from general sorting and hardcoding their position like it was before

Thanks

**Comment by valyala** [comment]
> This fix does not resolve the problem of incorrect sorting in the table view.

@Loori-R , could you fix this inconsistency in the follow-up commit?

> My proposal is that system fields such as _time, _msg, _stream, and _stream_id should be positioned at the top in the group view. Something like excluding them from general sorting and hardcoding their position like it was before

I don't like this idea, since it violates the rule of generic sorting of all the log fields by their name, and may complicate manual search of the needed field if you expect that the fields are sorted by name. Probably, it would be better to highlight additionally these fields in some way. For example, the [`_time` field](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) and the [`_msg` field](https://docs.victoriametrics.com/victorialogs/keyconcepts/#message-field) are already displayed by default in the Group view - see the screenshot below:

![Image](https://github.com/user-attachments/assets/e161e088-d933-42c5-99a5-2a1094087cb2)

Logs are grouped by the [`_stream` label](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) by default in the Group view, and all the `_stream` labels are visible on the screenshot above.

**Comment by valyala** [comment]
@Loori-R , it looks like the original issue is still present - the log fields at the JSON tab aren't sorted by name at [this playground link](https://play-vmlogs.victoriametrics.com/select/vmui/?#/?query=%7Btype%3DPullRequestEvent%7D&g0.range_input=1d&g0.end_input=2025-03-02T23%3A00%3A00&g0.relative_time=none&view=json). See that the `payload.*` fields are mixed with `actor.*` fields in the screenshot below:

![Image](https://github.com/user-attachments/assets/b2a3b473-ccfc-4a5b-8042-d7af2972839b)

This screenshot has been made from [v1.23.1-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Re-opening the issue again.
